### ISSUE TITLE
loaderUtils.parseQuery is not a function

### ISSUE THREAD

**Issue by FDiskas** [icfantv/angular-template-loader#1]
node_modules/angular-template-loader/index.js:8:29

**Comment by icfantv** [comment]
This project was never meant for public consumption.  Rather it was, as indicated by the NPM description, only used for an emergency patch on a remote project retrieval due to a bug in the project from which this project came.  You should not be using this at all.

**Comment by FDiskas** [comment]
Why not? It's do what it says and almost perfect :) :dango:

**Comment by FDiskas** [comment]
What is original library of this?

**Comment by icfantv** [comment]
Because I'm not maintaining it and am seriously considering deleting it.  If you want the original it's [ngtemplate-loader](https://github.com/WearyMonkey/ngtemplate-loader).  Just know there was a bug in the library around paths on Windows - which was the bug we needed to be fixed ASAP.

Unfortunately, NPM won't let me remove it from their repo because it breaks folks.  I should check on deprecation....
